### ISSUE TITLE
Do regular expressions match the entire input?

### ISSUE THREAD

**Issue by bethesque** [bethesque/pact-specification#16]
Should /\d/ match "MikeIsAwesome123@#!" or only "9"?

You can put /$\d^/ if you like but is it intuitive? Do all the implementations do the same thing?

**Comment by uglyog** [comment]
I don't think all implementations will do the same thing. But my opinion is
that /\d/ should match "abc9".

**Comment by mboudreau** [comment]
I agree with Ronald. If the use wants specificity, they can add ^ and $
around the expression.

**Comment by bethesque** [comment]
That's my gut feel too. We will need to add use cases to the pact spec to ensure that all the implementations treat the regular expressions the same way.
