### ISSUE TITLE
At least X feature

### ISSUE THREAD

**Issue by bethesque** [bethesque/pact-specification#17]
@uglyog, I'm not super keen on the way the current implementation of the 'at least' feature means we have to string parse the match value to work out how many items need to match.

https://github.com/bethesque/pact-specification/blob/version-2/testcases/request/body/array%20with%20at%20least%20two%20elements%20expected.json

Also, it seems that this would be better named "starting with". I was confused as to why this example was a failure until I realised that order mattered: https://github.com/bethesque/pact-specification/blob/version-2/testcases/request/body/array%20with%20at%20least%20one%20element%20but%20the%20element%20is%20different.json

I'm also not sure why we need to put in the number, as I'm pretty sure you pointed out that the number of elements in the expected array indicates how many we need to match?

**Comment by uglyog** [comment]
That was the initial idea I tried. Please refer to the discussion on #14

**Comment by uglyog** [comment]
Closed as it's been included in #14
