### ISSUE TITLE
Add example with array at top level

### ISSUE THREAD

**Issue by bethesque** [bethesque/pact-specification#18]
v1 and v2

**Comment by abhayachauhan** [comment]
I'd love to see a test case of using matchers on an array at the top level of the body.

Eg:

"body": [
          {
            "eventId": "45d80d13-d5a2-48d7-8353-cbb4c0eaabf5",
            "timestamp": "2014-06-30T01:37:41.0660548",
            "eventType": "SearchView"
          },
          {
            "eventId": "83f9262f-28f1-4703-ab1a-8cfd9e8249c9",
            "timestamp": "2014-06-30T01:37:52.2618864",
            "eventType": "DetailsView"
          },
          {
            "eventId": "3e83a96b-2a0c-49b1-9959-26df23f83aeb",
            "timestamp": "2014-06-30T01:38:00.8518952",
            "eventType": "SearchView"
          }
        ]


Should the matcher for eventId in the first index be:
          "$.body.[0].eventId": { "match": "type" } 
or
          "$.body[0].eventId": { "match": "type" }

**Comment by uglyog** [comment]
`"$.body[0].eventId": { "match": "type" }` is the correct form. I'll add examples.
