### ISSUE TITLE
Header key matching must be case insensitive

### ISSUE THREAD

**Issue by uglyog** [bethesque/pact-specification#4]
From [RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", paragraph 4.2, "Message Headers"](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by freewind** [comment]
:+1:  I found the same issue in the spec: https://github.com/bethesque/pact-specification/tree/version-1.1

> Request headers
>
> Exact string match for expected header names and values.

**Comment by uglyog** [comment]
This is implemented in V2
